apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-deployment
  namespace: hello
  labels:
    app: hello
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 100
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: dclwrnc/hello:3.0.0
          ports:
            - containerPort: 8085
              name: http-web-svc
          livenessProbe:
            httpGet:
              path: /
              port: http-web-svc
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http-web-svc
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello
spec:
  selector:
    app.kubernetes.io/name: hello
  ports:
    - name: hello-port
      protocol: TCP
      port: 8078
      targetPort: http-web-svc
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: hello-succeed-pre-sync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: fail
          image: alpine:latest
          command:
            - "sh"
            - "-c"
            - "echo"
            - "'success'"
      restartPolicy: Never
  backoffLimit: 2